### ISSUE TITLE
Save Nests in database to edit unknown names for future re-use

### ISSUE THREAD

**Issue by BadWolf0081** [M4d40/PMSFnestScript#18]
Great work on this script, love using it!

I was wondering if there would be a way to have the script simply save all detected nests in the database and allow us then to manually edit those names which it is missing and later only update the pokemon field for use?  having it check the database for the name before posting to discord?

**Comment by muckelba** [comment]
The nests are in the DB already. but editing the names in there doesnt make much sense since the script ususally overrides those entries. Luckily, the script generates a .csv file that you can edit, it will take the name from there each run

**Comment by BadWolf0081** [comment]
OH! Perfect solution! thank you!
