### ISSUE TITLE
Nest center should be inside the polygon even if it is concave

### ISSUE THREAD

**Issue by Mygod** [M4d40/PMSFnestScript#25]
Possible solution: https://blog.mapbox.com/a-new-algorithm-for-finding-a-visual-center-of-a-polygon-7c77e6492fbc

Related discussions: https://github.com/WatWowMap/MapJS/pull/206#issuecomment-697077872

**Comment by clburlison** [comment]
I dug into this a little bit and currently this project is already using a library that utilizes that formula ( https://github.com/Toblerity/Shapely). While it isn't calling the `polylabel` function directly it is indirectly getting the same polygon center point.

Tested with a few different values and really couldn't come up with a better solution than what is currently already implemented. It's possible two completely separate python developers implemented the initial project incorrectly...but it's much more likely mapbox's 2016 claim of "...guaranteeing the correct result in all cases." is false.

As it stands I have over 300 nests generated via this project and less than 15 of them have center points outside of the nest polygon. I stopped digging when I saw both libraries produced roughly the same results but sample code included below if anyone wants to look some more.

```python
#pip install python-polylabel
#pip install shapely
#pip install geojson

from geojson import (
    Feature,
    FeatureCollection,
    dumps
)

from polylabel import polylabel
from shapely.ops import polylabel as polylabel2
from shapely.geometry import shape
import json

NEST_NAMES = ['Foobar Park', 'Foobar2 Park', 'Foobar3 Park', 'Foobar4']
NEST_IDS = [605XXXX44]

with open("nests.json") as json_file:
    json_data = json.load(json_file)

for item in json_data['features']:
    if item['properties']['name'] in NEST_NAMES:
        print(item['properties']['name'])
        print(polylabel(item['geometry']['coordinates']))
        print(polylabel2(shape(item['geometry']), tolerance=10))
    if item['id'] in NEST_IDS:
        print(polylabel(item['geometry']['coordinates']))
```

**Comment by Mygod** [comment]
Have you set the precision properly? The default precision is 1.0 which is probably not what you want.

**Comment by Mygod** [comment]
```python
from geojson import (
    Feature,
    FeatureCollection,
    dumps
)

from polylabel import polylabel
from shapely.ops import polylabel as polylabel2
from shapely.geometry import shape
import json

with open("nests.json") as json_file:
    json_data = json.load(json_file)

for item in json_data['features']:
    print(item['properties']['name'])
    print(polylabel(item['geometry']['coordinates'], 1e-6))
    point = polylabel2(shape(item['geometry']), tolerance=1e-6)
    print(point)
    assert shape(item['geometry']).contains(point)
    print()
```

Changed precision/tolerance to 1e-6 (~0.1m). All the points are inside the polygon.

**Comment by Mygod** [comment]
Was this fixed?

**Comment by ccev** [comment]
v2 uses polylabel to correctly put markers inside polygons.
