### ISSUE TITLE
suggestion - allow option 1 (discord bot) to only display parks without a name

### ISSUE THREAD

**Issue by hunch-13** [M4d40/PMSFnestScript#35]
often folks will only need to tidy up missing names so having this as a toggle/option would speed up renaming of those

**Comment by LiquidArrogance** [comment]
Just came here to leave this suggestion XD

**Comment by ccev** [comment]
When I first did the script I actually had it default. But handling default names sucksssssssss if you want to do it the right way. I can take the shortcut, though. Should work 90% of the time

**Comment by hunch-13** [comment]
can you have the option be something like "where name = <default name var>" ?

**Comment by ccev** [comment]
yes. that's the shortcut way i was talking about

**Comment by ccev** [comment]
implemented in latest master.
