### ISSUE TITLE
Add Nest Report for Telegram

### ISSUE THREAD

**Issue by pogoteambrindisi** [M4d40/PMSFnestScript#38]
Hi, 

It would be nice if a nest report function could be added for Telegram. The concept is very similar to Discord. There are bots with associated tokens that could write the message in a group with a specific ID.

Thanks!

**Comment by jfberry** [comment]
Poracle can send nests to telegram triggered by nestwatcher - not quite the same (as they are individual alerts per nest) but may help you achieve what you want

**Comment by ccev** [comment]
That is a good solution to the issue. I have no interest in adding Telegram support
