### ISSUE TITLE
Timestamp Suggestion

### ISSUE THREAD

**Issue by PartTimeJS** [M4d40/PMSFnestScript#39]
{current_time} puts "Today at x:xx PM" in the embed which remains that way whether "Today" was yesterday or days ago. . Can this be changed to the full date? i.e. "Thursday, January 15th x:xx pm"

**Comment by ccev** [comment]
{current_time} is just a datetime object. You can put it in the embed's timestamp. Discord itself then handles the "Today at xxx" part based on the user's Timezone. If it's been a day since updating, it'd also display "Yesterday at xxx".
