### ISSUE TITLE
Only Send Webhooks when nest is being updated

### ISSUE THREAD

**Issue by bbdoc** [M4d40/PMSFnestScript#47]
At the moment, webhooks are being sent for the whole area as soon as only 1 nest from this area gets updated. This means the receiver (PoracleJS) would need to keep a cache of what was already received so it doesn't send double notifications. 

Could you please change this behaviour so that webhooks are only sent when a nest is actually updated. This would make the development on the receiver side a lot easier.

Thanks

**Comment by jfberry** [comment]
Poracle keeps a cache to eliminate dupes, this can be closed
