### ISSUE TITLE
tools.py option 3 not actually updating area_data json files

### ISSUE THREAD

**Issue by Zyahko** [M4d40/PMSFnestScript#54]
When I run tools.py and choose option 3 to update some nest names for an area. It prompts for the y/n for areas that have a name change but when I tell it y it doesn't seem to actually update that areas json file in the area_data folder. It also doesn't throw an error or anything it just acts like it ran it fine after I answer the y/n.

**Comment by ccev** [comment]
Fixed in latest, thank you
